steps:
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/tijlk/money-flow.git', 'app']
  - name: 'gcr.io/cloud-builders/zip'
    args: ['-r', 'app.zip', 'app']

options:
  logging: CLOUD_LOGGING_ONLY